### ISSUE TITLE
Error - shader model 3.0 not supported by driver

### ISSUE THREAD

**Issue by gmgj** [mstrange86/milkdrop2_mmport#1]
Thanks for doing the milkdrop2 port.

This is not a request, just a notification.  It won't work for me    
MediaMonkey latest 4.1.14.183
Win 10 64 Home-  Latest updates
GeForce GT 730 (2014) video card
Direct X runtime version 12.0
Driver version 378.92 
Direct#D API 12
Direct 3d feature level 11_0
64 bit
Video BIOS 80.28.78.00.48
see the file

![gt730](https://cloud.githubusercontent.com/assets/1705834/24370817/c4d843f0-12f6-11e7-9ff8-fdc3df0a6ee6.PNG)

I have written dlls before. I will test this if you ever want to fix it.

**Comment by mstrange86** [comment]
PS model 3.0 has been around since Nvidia's 2004 cards so the issue is not due to hardware. I have a newer Nvidia card and have had no issues so my first impulse is that there is a configuration issue.

Specifically, many machines have integrated Intel graphics processors that are used to run graphics in processes by default and only migrated to the Nvidia card in specific circumstances. 

That is clearly the root cause here: https://hydrogenaud.io/index.php?PHPSESSID=u9fk86a7qco86immjrh03l0is0&topic=101247.msg836499#msg836499

On my computer I can configure whether integrated graphics are used at all in the motherboard BIOS. Setting it to "dedicated" will exclusively use the graphics card. I would suggest you investigate that; you can also disable the shader model check altogether in the options by choosing a value < shader model 3.

HTH,
Matt

**Comment by gmgj** [comment]
Thanks for the response. 
I extracted the install file milkdrop2mmport_%282%29.mmip and looked at the contents.  I do not see 
vis_milk2.dll anywhere or any of the other directories, example Milkdrop2

ZipFile=fso.BuildPath(SDB.CurrentAddonInstallRoot, "Plugins\Milkdrop2\favorite_presets_2013_12.zip")
' The folder the contents should be extracted to.
ExtractTo=fso.BuildPath(SDB.CurrentAddonInstallRoot, "Plugins\Milkdrop2\")

Could something be wrong  with the install?  

The scenario you describe is exactly what happens when you just plug in a graphics card on most machines that were initially configured to run with integrated graphics.  When I first set up the card, I saw something like Intel HD graphics and the GT 730 in Device Manager. In my case, I set the Bios to use the graphics card (in this machines BIOS its something like, "Use the graphics card if its there")  I have enclosed a snippet of device manager to show that I see only the GT 730.  I have also include the output from dxdiag that shows the graphics card.  When you let windows find a driver for the card, it installs a working driver; but, I contacted the vendor and got the driver that they suggested.  


![devicemanger730](https://cloud.githubusercontent.com/assets/1705834/24410195/73d52b08-13a0-11e7-9c4d-78e676319c91.png)
[DxDiag.txt](https://github.com/mstrange86/milkdrop2_mmport/files/875961/DxDiag.txt)

I use 2 monitors, if that makes any difference.
The install says its copying files, but, they are not there,  is this a permissions problem?  I vaguely recollect that they change what you can do under program files

**Comment by mstrange86** [comment]
The DLL must be installed because that error message is contained inside of the DLL. I believe it installs to %appdata%\MediaMonkey\Plugins by default. I also have a multimonitor setup but I've never had issues with that.

If you're familiar with the process of compiling DLLs you could compile this one in debug mode then copy it to the plugin path and attach the debugger to the running visualization process to see what the exact failure code is for compiling that pixel shader. That is probably the most direct way to solve the problem. If you do streaming or use a remote desktop client like Teamviewer I believe some implementations have virtual display hardware that might also be involved here.

**Comment by gmgj** [comment]
I was going to build the debug dll.
I installed 

Microsoft DirectX SDK (June 2010)
VC community edition
Windows 10 SDK

I thought what the F&(*&, I will see if Milkdrop2 works.
The desktop is working.
 
One machine down.  I will get back to you after I try a few things on the laptop

FYI, the install instructions per the Mediamonkey guys is

Try this:
1. Start MMW as Administrator
2. Go to Tools -> Extensions and uninstall Milkdrop2
3. Restart MMW as Administrator
4. Go to Tools -> Extensions -> ADD
5. Locate Milkdrop2 plugin installation
6. Disable Per User Plugin installation
7. restart MMW

**Comment by mstrange86** [comment]
Thx for the update. I know it does a pre-check for the DirectX runtime install and shows a popup if it isn't there so it must have been installed to some degree already.

My best guess is that the DirectX runtime installation was corrupted in some way.
